config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # guest_sign_in用のルート
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

# 新規登録失敗時のリロードエラーを防ぐ
 get "users" => redirect("/users/sign_up")

 # Public側の記述
   root to: "public/homes#top"
   get 'homes/about', to: 'public/homes#about'

  scope module: :public do
    resources :users, only: [:edit, :show, :update, :destroy] do
      member do
        get :favorites
      end
      resources :messages, only: [:new, :index, :create, :destroy]
      collection do
        get :mypage
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get 'searches/search', to: 'searches#search'
  end

  # admin側の記述
  namespace :admin do
    resources :message_text, only: [:new, :create, :destroy]
    resources :moods, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :post_moods, dependent: :destroy
  has_many :posts, through: :post_moods
end

app/controllers/admin/moods_controller.rb
class Admin::MoodsController < ApplicationController
  
  def new
    @mood = Mood.new
    @moods = Mood.all
  end
  
  def create
    @mood = Mood.new(mood_params)
    if @mood.save
      redirect_to request.referer, notice: '追加に成功しました。'
    else
      render :new, notice: '失敗しました。'
    end
    
  end

  def destroy
    mood = Mood.find(params[:id])
    mood.destroy
    redirect_to request.referer
  end
  
  private
  
  def mood_params
    params.require(:mood).permit(:name, :color)
  end

end

app/helpers/admin/moods_helper.rb
module Admin::MoodsHelper
end

app/views/admin/moods/new.html.erb
<div class='container'>
  <div class="card mx-auto mt-4 shadow-lg" style="max-width: 900px;">
    <div class="mx-auto py-4">
      <div class="ml-3">
        <strong>気分一覧</strong>
      </div>
      <div class="d-flex flex-wrap mood-content">
        <% @moods.each do |mood| %>
          <p class="px-2">
            <span class="mood-color" style="background-color: <%= mood.color %>; ">
              <%= mood.name %>
            </span>
            <%= link_to "削除", admin_mood_path(mood), method: :delete, class: "btn btn-light m-1" %>
          </p>
        <% end %>
      </div>
      <%= form_with model: @mood, url: admin_moods_path, local: true do |f| %>
        <div class="ml-3">
          <strong><%= f.label :name, "新しい気分の作成" %></strong>
        </div>
        <div class="m-3">
          <%= f.text_area :name, class: 'form-control' %>
        </div>
        <div class="col-4">
          <%= f.color_field :color, class: 'form-control' %>
        </div>
        <div class="m-3">
          <%= f.submit class: 'btn btn-outline-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>