config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # guest_sign_in用のルート
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

# 新規登録失敗時のリロードエラーを防ぐ
 get "users" => redirect("/users/sign_up")

 # Public側の記述
   root to: "public/homes#top"
   get 'homes/about', to: 'public/homes#about'

  scope module: :public do
    resources :users, only: [:edit, :show, :update, :destroy] do
      member do
        get :favorites
      end
      resources :messages, only: [:new, :index, :create, :destroy]
      collection do
        get :mypage
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get 'searches/search', to: 'searches#search'
  end

  # admin側の記述
  namespace :admin do
    resources :message_text, only: [:new, :create, :destroy]
    resources :moods, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :posts, dependent: :destroy
 has_many :sent_messages, class_name: "Message", foreign_key: "sender_id", dependent: :destroy
 has_many :received_messages, class_name: "Message", foreign_key: "receiver_id", dependent: :destroy
 has_many :comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 has_many :active_relationships, class_name: "Relationship", foreign_key: 'follower_id', dependent: :destroy
 has_many :followings, through: :active_relationships, source: :followed
 has_many :passive_relationships, class_name: "Relationship", foreign_key: 'followed_id', dependent: :destroy
 has_many :followers, through: :passive_relationships, source: :follower
 has_one_attached :profile_image

 validates :name, presence: true
 validates :profile_image, content_type: {in:[:png, :jpg, :jpeg], message: "はpng, jpg, jpegいずれかの形式にして下さい"}
 validates :introduction, length: { maximum: 40 }

  # ゲストログインユーザーの記述↓
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  # プロフィール画像のサイズ調整定義＆デフォルト画像の差し込み
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end

  # 検索の際に完全一致と部分一致で検索がかかるように
  def self.search_for(content,method)
    if method == 'perfect'
      User.where(name: content)
    else
      User.where('name LIKE ?', '%' +  content  + '%')
    end
  end

  # フォロー・アンフォロー・フォローの有無を確認するメソッド↓
  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
  
   # 昨日の投稿を取得
  def yesterday_post
    yesterday = Time.zone.today - 1
    posts.find_by(created_at: yesterday.all_day)
  end
  
  # 過去３日間のメッセージを取得
  def three_days_received_messages
    three_days_ago = Time.zone.today - 3
    received_messages.where(created_at: three_days_ago.beginning_of_day..Date.today.end_of_day)
  end
  
  # 過去3日間で送ったメッセージを表示
    def three_days_sent_messages
      three_days_ago = Time.zone.today - 3
      sent_messages.where(created_at: three_days_ago.beginning_of_day..Date.today.end_of_day)
    end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :authenticate_admin!

  def index
    @users = User.order(created_at: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page])
    @comments = @user.comments
  end

  def edit
  end

  def update
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "ユーザーを退会させました"
    redirect_to admin_users_path
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<div class='container'>
  <div class="card mx-auto mt-4 shadow-lg" style="max-width: 900px;">
    <div class="mx-auto py-4">
      <h4>ユーザー一覧</h4>
    </div>
    <% @users.each do |user| %>
      <div class="row justify-content-center py-3">
        <%= link_to admin_user_path(user) do %>
          <%= render "public/users/name",  user: user %>
        <% end %>
      </div>
    <% end %>
    <div class="row justify-content-center py-3">
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="card mx-auto mt-4 shadow-lg" style="max-width: 900px;">
    <div class="mx-auto py-4">
      <%= render "public/users/name",  user: @user %>
      <div class="text-center py-2 ">
        <%= link_to "退会させる",admin_user_path(@user),method: :delete,class: "btn btn-danger", "data-confirm"=> "本当に退会させますか？" %>
      </div>
      <div class ="pl-3">
        <p>送ったコメント</p>
        <% if @comments.present? %>
          <% @comments.each do |comment| %>
           <p><%= comment.body %>　⇦ <%= comment.post.user.name %>さんに
           <%= link_to "削除",post_comment_path(comment.post, comment),method: :delete,class: "btn btn-outline-danger", "data-confirm"=> "本当に削除しますか？" %>
           </p>
          <% end %>
        <% else %>
          <p>送ったコメントはありません。</p>
        <% end %>
      </div>
      <!--過去の日記-->
      <% @posts.each do |post| %>
        <% if post.post_image.attached? %>
          <!--写真背景の日記-->
          <div class="mx-auto">
            <%= link_to admin_post_path(post) do %>
              <div class="mb-2 background-image-container">
                <%= image_tag post.get_post_image, class: "background-image" %>
                <div class="overlay-content">
                  <p><%= l post.created_at, format: :long %>の<%= post.user.name %>さんの１行日記</p>
                  <p><%= post.body %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% else %>
          <!--気分カラー背景の日記-->
          <%= link_to admin_post_path(post) do %>
            <div class="mood-container m-md-3" style="background: <%= post.background_color %>;">
              <div class="post-body">
                <p><%= l post.created_at, format: :long %>の<%= post.user.name %>さんの１行日記</p>
                <p><%= post.body %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%= paginate @posts %>
    </div>
  </div>
</div>