config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # guest_sign_in用のルート
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

# 新規登録失敗時のリロードエラーを防ぐ
 get "users" => redirect("/users/sign_up")

 # Public側の記述
   root to: "public/homes#top"
   get 'homes/about', to: 'public/homes#about'

  scope module: :public do
    resources :users, only: [:edit, :show, :update, :destroy] do
      member do
        get :favorites
      end
      resources :messages, only: [:new, :index, :create, :destroy]
      collection do
        get :mypage
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get 'searches/search', to: 'searches#search'
  end

  # admin側の記述
  namespace :admin do
    resources :message_text, only: [:new, :create, :destroy]
    resources :moods, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message_text.rb
class MessageText < ApplicationRecord
  has_many :messages,dependent: :destroy
end

app/controllers/admin/message_text_controller.rb
class Admin::MessageTextController < ApplicationController
  def new
    @message_text = MessageText.new
    @message_texts = MessageText.all
  end
  
  def create
    @message_text = MessageText.new(message_text_params)
    if @message_text.save
      redirect_to request.referer, notice: '追加に成功しました。'
    else
      render :new, notice: '失敗しました。'
    end
  end
  
  def destroy
    message_text = MessageText.find(params[:id])
    message_text.destroy
    redirect_to request.referer
  end
  
  private
  
  def message_text_params
    params.require(:message_text).permit(:content)
  end
end

app/helpers/admin/message_text_helper.rb
module Admin::MessageTextHelper
end

app/views/admin/message_text/new.html.erb
<div class='container'>
  <div class="card mx-auto mt-4 shadow-lg" style="max-width: 900px;">
    <div class="mx-auto py-4">
      <p><strong>メッセージ一覧</strong></p>
      <% @message_texts.each do |message_text| %>
        <p>
          <%= message_text.content %>
          <%= link_to "削除", admin_message_text_path(message_text), method: :delete, class: "btn btn-light m-1" %>
        </p>
      <% end %>
      <div class="mx-auto py-4">
        <%= form_with model: @message_text, url: admin_message_text_index_path, local: true do |f| %>
          <strong><%= f.label :content, "新しくメッセージの選択肢を作成" %></strong>
          <%= f.text_area :content, class: 'form-control' %>
          <div class="d-flex justify-content-end pt-2">
            <%= f.submit class: 'btn btn-outline-dark' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>