config/routes.rb
Rails.application.routes.draw do


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # guest_sign_in用のルート
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

# 新規登録失敗時のリロードエラーを防ぐ
 get "users" => redirect("/users/sign_up")

 # Public側の記述
   root to: "public/homes#top"
   get 'homes/about', to: 'public/homes#about'

  scope module: :public do
    resources :users, only: [:edit, :show, :update, :destroy] do
      member do
        get :favorites
      end
      resources :messages, only: [:new, :index, :create, :destroy]
      collection do
        get :mypage
      end
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    get 'searches/search', to: 'searches#search'
  end

  # admin側の記述
  namespace :admin do
    resources :message_text, only: [:new, :create, :destroy]
    resources :moods, only: [:new, :create, :destroy]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :posts, only: [:show, :destroy]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <%= obj.errors.count %>件のエラーが発生しました
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_notice.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-center"><%= message %></div>
<% end %>

app/views/layouts/_sideber.html.erb
<ul class="nav-list">
  <% if user_signed_in? %>
    <% if current_user.guest_user? %>
      <!-- ゲストユーザー用のリンク -->
      <li class="nav-list-item">
        <%= link_to posts_path do %>
          <i class="fa-solid fa-house"></i>　みんなの１行
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to  homes_about_path do %>
          <i class="fa-regular fa-address-card"></i>　About
        <% end %>
      </li>
      <li class="nav-list-item ">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa-solid fa-right-from-bracket"></i>　ログアウト
        <% end %>
      </li>
    <% else %>
      <!-- ログインユーザー用のリンク -->
      <li class="nav-list-item">
        <%= link_to posts_path do %>
          <i class="fa-solid fa-house"></i>
          <span class="d-none d-lg-inline">　みんなの１行</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to mypage_users_path do %>
          <i class="fa-solid fa-user"></i>
          <span class="d-none d-lg-inline">　マイページ</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to new_post_path do %>
          <i class="fa-regular fa-square-plus"></i>
          <span class="d-none d-lg-inline">　日記を書く</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to edit_user_path(current_user) do %>
          <i class="fa-solid fa-gear"></i>
          <span class="d-none d-lg-inline">　プロフィール編集</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa-solid fa-right-from-bracket"></i>
          <span class="d-none d-lg-inline">　ログアウト</span>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <% if admin_signed_in? %>
      <li class="nav-list-item">
        <%= link_to admin_users_path do %>
          <i class="fa-solid fa-user-group"></i>
          <span class="d-none d-lg-inline">　ユーザー一覧</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to new_admin_mood_path do %>
          <i class="fa-regular fa-heart"></i>
          <span class="d-none d-lg-inline">　気分変更</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to new_admin_message_text_path do %>
          <i class="fa-solid fa-pen-to-square"></i>
          <span class="d-none d-lg-inline">　メッセージ追加</span>
        <% end %>
      </li>
      <li class="nav-list-item">
        <%= link_to destroy_admin_session_path, method: :delete do %>
          <i class="fa-solid fa-right-from-bracket"></i>
          <span class="d-none d-lg-inline">　ログアウト</span>
        <% end %>
      </li>
    <% else %>
    <!-- ログアウト状態のリンク -->
      <li class="nav-list-item"><%= link_to "新規登録", new_user_registration_path %></li>
      <li class="nav-list-item"><%= link_to "ログイン", new_user_session_path %></li>
      <li class="nav-list-item"><%= link_to "About", homes_about_path %></li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IchigyoDiary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/76f4db3613.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-3 col-lg-2 d-md-block sidebar">
          <% if current_user&.guest_user? %>
            <h1 class="d-none d-lg-inline logo mx-3">1Gyo diary</h1>
          <% else %>
            <h1 class="d-none d-lg-inline logo mx-3">
              <%= link_to "1Gyo diary", root_path %>
            </h1>
          <% end %>
          <%= render "layouts/sideber" %>
        </nav>
        <main class="col-md-9 ms-sm-auto col-lg-10">
          <div class="row justify-content-center">
            <% flash.each do |message_type, message| %>
              <div class="flash-message <%= message_type %>"><%= message %></div>
            <% end %>
          </div>
          <%= yield %>
        </main>
      </div>
    </div>
  </body>
</html>